# Generated by Django 5.1.7 on 2025-03-26 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpBISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=200)),
                ('current_address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=50)),
                ('designation', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('aadhar_card', models.CharField(max_length=200)),
                ('date_of_join', models.CharField(max_length=200)),
                ('work_location', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
            ],
        ),
    ]
