# Generated by Django 5.1.7 on 2025-04-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
