# Generated by Django 5.1.7 on 2025-03-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Annual', 'Annual Leave'), ('Maternity', 'Maternity Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('apply_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('total_leave', models.IntegerField()),
                ('remaining_leave', models.IntegerField()),
                ('availed_leave', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='HR_App.employeebisp')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.employeebisp')),
            ],
        ),
    ]
