# Generated by Django 5.1.7 on 2025-04-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0002_leave_is_half_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebisp',
            name='availed_leave',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeebisp',
            name='remaining_leave',
            field=models.FloatField(default=12.0),
        ),
    ]
