# Generated by Django 5.1.7 on 2025-04-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0003_alter_employeebisp_availed_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_days',
            field=models.FloatField(default=1.0),
        ),
    ]
