# Generated by Django 5.1.7 on 2025-04-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0004_leave_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='compensatory_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='compensatory_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
