# Generated by Django 5.1.7 on 2025-04-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0005_leave_compensatory_off_leave_compensatory_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hidden', 'Hidden')], default='active', max_length=10),
        ),
    ]
