# Generated by Django 5.1.7 on 2025-04-07 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0006_leavetype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional: Restrict to a specific department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_App.department'),
        ),
    ]
