# Generated by Django 5.1.7 on 2025-04-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0008_handbookpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebisp',
            name='handbook_status',
            field=models.CharField(choices=[('Not Acknowledge', 'Not Acknowledge'), ('Acknowledge', 'Acknowledge')], default='Not Acknowledge', max_length=20),
        ),
    ]
