# Generated by Django 5.1.7 on 2025-04-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0009_employeebisp_handbook_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Acknowledge', 'Acknowledge'), ('Pending', 'Pending')], max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.employeebisp')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_App.handbookpdf')),
            ],
        ),
    ]
