# Generated by Django 5.1.7 on 2025-04-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_App', '0010_handbookacknowledgement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebisp',
            name='handbook_status',
        ),
        migrations.AlterField(
            model_name='handbookacknowledgement',
            name='status',
            field=models.CharField(choices=[('Not Acknowledge', 'Not Acknowledge'), ('Acknowledge', 'Acknowledge')], default='Not Acknowledge', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='handbookacknowledgement',
            unique_together={('pdf', 'employee')},
        ),
    ]
